name: My2025App

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v4
      with:
        path: ~/.docker/buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -f 2025/Dockerfile -t my-blazor-app .

    - name: Push image to Docker Hub
      if: github.ref == 'refs/heads/master'
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        docker tag my-blazor-app abbz290/2025d:latest
        docker push abbz290/2025d:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: SSH into Local Host and Deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 80  # SSH default port
        script: |
          # Login to Docker Hub
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          
          # Pull the latest Docker image
          docker pull abbz290/2025d:latest || { echo "Docker pull failed"; exit 1; }
          
          # Stop and remove the existing container
          docker stop 2025d-app || true
          docker rm 2025d-app || true
          
          # Run the new container
          docker run -d \
            --name 2025d-app \
            -p 8080:8080 \ # Expose port 8080 (adjust as needed)
            --restart unless-stopped \
            abbz290/2025d:latest || { echo "Docker run failed"; exit 1; }
